deployment:
  tasks:
    - export DEPLOYPATH=/home/vehsuqnb/vehsf-server
    - cd $DEPLOYPATH
    - /bin/rm -rf node_modules
    - /bin/npm install --production
    - /bin/npm start || true
    - touch tmp/restart.txt
